<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class UniversalCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds idempotently.
     */
    public function run(): void
    {
        // 1. Initial 11 Universal Categories
        $categoriesData = [
            [
                'title'       => 'Electronics',
                'handle'      => 'electronics',
                'description' => 'Smart gadgets, audio gear, and cutting-edge electronic accessories.',
                'sort_order'  => 1,
                'status'      => true,
            ],
            [
                'title'       => 'Fashion',
                'handle'      => 'fashion',
                'description' => 'Contemporary apparel, footwear, and stylish everyday clothing.',
                'sort_order'  => 2,
                'status'      => true,
            ],
            [
                'title'       => 'Beauty',
                'handle'      => 'beauty',
                'description' => 'Skin care essentials, cosmetics, and rejuvenating personal care.',
                'sort_order'  => 3,
                'status'      => true,
            ],
            [
                'title'       => 'Home & Living',
                'handle'      => 'home-living',
                'description' => 'Kitchenware, organizers, and home comfort improvement items.',
                'sort_order'  => 4,
                'status'      => true,
            ],
            [
                'title'       => 'Grocery',
                'handle'      => 'grocery',
                'description' => 'Pantry staples, organic honey, teas, and fresh daily provisions.',
                'sort_order'  => 5,
                'status'      => true,
            ],
            [
                'title'       => 'Accessories',
                'handle'      => 'accessories',
                'description' => 'Bags, watches, wallets, and premium travel accessories.',
                'sort_order'  => 6,
                'status'      => true,
            ],
            [
                'title'       => 'Health',
                'handle'      => 'health',
                'description' => 'Wellness products, first aid supplies, and daily health monitors.',
                'sort_order'  => 7,
                'status'      => true,
            ],
            [
                'title'       => 'Sports',
                'handle'      => 'sports',
                'description' => 'Fitness equipment, athletic gear, and outdoor workout accessories.',
                'sort_order'  => 8,
                'status'      => true,
            ],
            [
                'title'       => 'Books',
                'handle'      => 'books',
                'description' => 'Personal growth, business strategies, and engaging reading books.',
                'sort_order'  => 9,
                'status'      => true,
            ],
            [
                'title'       => 'Automotive',
                'handle'      => 'automotive',
                'description' => 'Car care supplies, interior gadgets, and safety accessories.',
                'sort_order'  => 10,
                'status'      => true,
            ],
            [
                'title'       => 'Toys & Games',
                'handle'      => 'toys-games',
                'description' => 'Educational puzzles, building blocks, and fun family board games.',
                'sort_order'  => 11,
                'status'      => true,
            ],
        ];

        $categoryMap = [];
        foreach ($categoriesData as $catData) {
            $seedImage = '/images/categories/' . $catData['handle'] . '.svg';
            $existingCat = Category::where('handle', $catData['handle'])->first();

            if (!$existingCat) {
                $cat = Category::create([
                    'title'        => $catData['title'],
                    'handle'       => $catData['handle'],
                    'description'  => $catData['description'],
                    'sort_order'   => $catData['sort_order'],
                    'status'       => $catData['status'],
                    'image'        => $seedImage,
                    'banner_image' => $seedImage,
                ]);
            } else {
                // Safe preservation of admin custom media
                $isSeedOrEmptyImage = empty($existingCat->image)
                    || $existingCat->image === '/images/banners/all-collection.jpg'
                    || $existingCat->image === 'images/banners/all-collection.jpg'
                    || $existingCat->image === '/images/placeholder.webp'
                    || str_starts_with($existingCat->image, '/images/categories/');

                $isSeedOrEmptyBanner = empty($existingCat->banner_image)
                    || $existingCat->banner_image === '/images/banners/all-collection.jpg'
                    || $existingCat->banner_image === 'images/banners/all-collection.jpg'
                    || $existingCat->banner_image === '/images/placeholder.webp'
                    || str_starts_with($existingCat->banner_image, '/images/categories/');

                $existingCat->update([
                    'title'        => $catData['title'],
                    'description'  => $catData['description'],
                    'sort_order'   => $catData['sort_order'],
                    'status'       => $catData['status'],
                    'image'        => $isSeedOrEmptyImage ? $seedImage : $existingCat->image,
                    'banner_image' => $isSeedOrEmptyBanner ? $seedImage : $existingCat->banner_image,
                ]);
                $cat = $existingCat;
            }

            $categoryMap[$cat->handle] = $cat;
        }

        // 2. Initial Universal Products (5 products per category = 55 products total)
        $productsData = [
            // --- Electronics ---
            [
                'title'             => 'Smart Watch Pro 4',
                'slug'              => 'smart-watch-pro-4',
                'sku'               => 'ELEC-SWP4-01',
                'category_handle'   => 'electronics',
                'regular_price'     => 3500,
                'sale_price'        => 2850,
                'cost_price'        => 2100,
                'stock'             => 45,
                'sizes'             => ['Black', 'Silver', 'Midnight Blue'],
                'short_description' => 'Full-touch AMOLED display with heart rate and fitness tracking.',
                'description'       => '<p>Experience next-level connectivity with the Smart Watch Pro 4. Featuring a vibrant AMOLED touchscreen, all-day battery life, IP68 water resistance, and real-time biometric tracking.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Wireless Earbuds',
                'slug'              => 'wireless-earbuds',
                'sku'               => 'ELEC-WE-02',
                'category_handle'   => 'electronics',
                'regular_price'     => 1800,
                'sale_price'        => 1450,
                'cost_price'        => 950,
                'stock'             => 60,
                'sizes'             => ['White', 'Matte Black'],
                'short_description' => 'True wireless stereo sound with active environmental noise cancellation.',
                'description'       => '<p>High-fidelity audio with seamless Bluetooth 5.3 pairing, ergonomic fit, and an ultra-compact fast-charging case delivering up to 28 hours of total playback.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Bluetooth Headphones',
                'slug'              => 'bluetooth-headphones',
                'sku'               => 'ELEC-BH-03',
                'category_handle'   => 'electronics',
                'regular_price'     => 2500,
                'sale_price'        => 1990,
                'cost_price'        => 1300,
                'stock'             => 35,
                'sizes'             => ['Over-Ear Black', 'Over-Ear Gray'],
                'short_description' => 'Deep bass studio-quality over-ear wireless headphones with cushioned ear cups.',
                'description'       => '<p>Engineered for all-day listening comfort with memory foam padding, punchy dynamic drivers, and 40 hours of continuous wireless playback.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Portable Bluetooth Speaker',
                'slug'              => 'portable-bluetooth-speaker',
                'sku'               => 'ELEC-PBS-04',
                'category_handle'   => 'electronics',
                'regular_price'     => 2200,
                'sale_price'        => 1750,
                'cost_price'        => 1150,
                'stock'             => 50,
                'sizes'             => [],
                'short_description' => 'Rugged waterproof wireless speaker with 360-degree room-filling audio.',
                'description'       => '<p>Compact cylindrical design with reinforced silicone bumpers, IPX7 waterproof rating, and a built-in lanyard for outdoor adventures.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Smartphone Holder',
                'slug'              => 'smartphone-holder',
                'sku'               => 'ELEC-SPH-05',
                'category_handle'   => 'electronics',
                'regular_price'     => 650,
                'sale_price'        => 490,
                'cost_price'        => 280,
                'stock'             => 80,
                'sizes'             => ['Desk Mount', 'Car Vent Mount'],
                'short_description' => 'Multi-angle adjustable aluminum alloy phone cradle for desk and vehicle.',
                'description'       => '<p>Foldable anti-slip desk stand providing sturdy viewing angles for video calls, desktop productivity, and in-car hands-free navigation.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],

            // --- Fashion ---
            [
                'title'             => "Men's Cotton T-Shirt",
                'slug'              => 'mens-cotton-t-shirt',
                'sku'               => 'FASH-MCT-01',
                'category_handle'   => 'fashion',
                'regular_price'     => 750,
                'sale_price'        => 590,
                'cost_price'        => 340,
                'stock'             => 120,
                'sizes'             => ['M', 'L', 'XL', 'XXL'],
                'short_description' => '100% combed organic cotton breathable crewneck t-shirt.',
                'description'       => '<p>Soft, durable, and pre-shrunk cotton fabric designed for everyday ease, casual styling, and long-lasting shape retention.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => "Women's Casual Shirt",
                'slug'              => 'womens-casual-shirt',
                'sku'               => 'FASH-WCS-02',
                'category_handle'   => 'fashion',
                'regular_price'     => 1200,
                'sale_price'        => 950,
                'cost_price'        => 600,
                'stock'             => 75,
                'sizes'             => ['S', 'M', 'L'],
                'short_description' => 'Relaxed fit lightweight breathable linen-blend casual button-down shirt.',
                'description'       => '<p>Effortlessly chic styling suitable for office, weekend outings, and everyday comfort with a tailored buttoned cuff.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Premium Polo Shirt',
                'slug'              => 'premium-polo-shirt',
                'sku'               => 'FASH-PPS-03',
                'category_handle'   => 'fashion',
                'regular_price'     => 1100,
                'sale_price'        => 890,
                'cost_price'        => 520,
                'stock'             => 90,
                'sizes'             => ['M', 'L', 'XL'],
                'short_description' => 'Classic pique knit polo shirt with ribbed collar and tailored sleeve hems.',
                'description'       => '<p>Combines smart semi-formal looks with all-day breathability. Made from double-dyed premium cotton pique yarn.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Casual Sneakers',
                'slug'              => 'casual-sneakers',
                'sku'               => 'FASH-CS-04',
                'category_handle'   => 'fashion',
                'regular_price'     => 2400,
                'sale_price'        => 1890,
                'cost_price'        => 1200,
                'stock'             => 40,
                'sizes'             => ['Size 40', 'Size 41', 'Size 42', 'Size 43'],
                'short_description' => 'Cushioned street style sneakers with non-slip rubber traction sole.',
                'description'       => '<p>Engineered for lightweight daily walking comfort, equipped with memory foam insoles and a breathable mesh upper.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => "Men's Casual Hoodie",
                'slug'              => 'mens-casual-hoodie',
                'sku'               => 'FASH-MCH-05',
                'category_handle'   => 'fashion',
                'regular_price'     => 1800,
                'sale_price'        => 1390,
                'cost_price'        => 880,
                'stock'             => 65,
                'sizes'             => ['M', 'L', 'XL'],
                'short_description' => 'Heavyweight fleece pullover hoodie with kangaroo pocket and drawstring hood.',
                'description'       => '<p>Warm, plush brushed fleece lining with ribbed elastic cuffs and hem for cozy winter comfort and stylish layering.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],

            // --- Beauty ---
            [
                'title'             => 'Vitamin C Face Serum',
                'slug'              => 'vitamin-c-face-serum',
                'sku'               => 'BEAU-VCS-01',
                'category_handle'   => 'beauty',
                'regular_price'     => 1200,
                'sale_price'        => 890,
                'cost_price'        => 450,
                'stock'             => 85,
                'sizes'             => ['30ml Bottle', '50ml Bottle'],
                'short_description' => 'Brightening serum enriched with Hyaluronic Acid and Vitamin E.',
                'description'       => '<p>Formulated to reduce dark spots, boost skin radiance, and stimulate natural collagen production for a smoother, firmer complexion.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Matte Lipstick',
                'slug'              => 'matte-lipstick',
                'sku'               => 'BEAU-ML-02',
                'category_handle'   => 'beauty',
                'regular_price'     => 650,
                'sale_price'        => 480,
                'cost_price'        => 220,
                'stock'             => 100,
                'sizes'             => ['Ruby Red', 'Nude Rose', 'Velvet Plum'],
                'short_description' => 'Velvety matte liquid lipstick with up to 16 hours of smudge-proof wear.',
                'description'       => '<p>Delivers intense, weightless pigmentation without drying the lips. Infused with Vitamin E and shea butter extract.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Gentle Face Wash',
                'slug'              => 'gentle-face-wash',
                'sku'               => 'BEAU-GFW-03',
                'category_handle'   => 'beauty',
                'regular_price'     => 550,
                'sale_price'        => 420,
                'cost_price'        => 210,
                'stock'             => 90,
                'sizes'             => ['100ml Tube', '150ml Pump'],
                'short_description' => 'Hydrating daily facial cleanser suitable for all sensitive skin types.',
                'description'       => '<p>Sulfate-free formulation that lifts dirt and excess oil while preserving the natural skin barrier moisture.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Moisturizing Cream',
                'slug'              => 'moisturizing-cream',
                'sku'               => 'BEAU-MC-04',
                'category_handle'   => 'beauty',
                'regular_price'     => 850,
                'sale_price'        => 690,
                'cost_price'        => 380,
                'stock'             => 70,
                'sizes'             => ['50g Jar', '100g Jar'],
                'short_description' => 'Deep nourishment day and night cream with ceramides and aloe vera.',
                'description'       => '<p>Locks in continuous 24-hour hydration, soothing dryness and restoring skin suppleness without a greasy after-feel.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Hair Care Set',
                'slug'              => 'hair-care-set',
                'sku'               => 'BEAU-HCS-05',
                'category_handle'   => 'beauty',
                'regular_price'     => 1600,
                'sale_price'        => 1250,
                'cost_price'        => 750,
                'stock'             => 45,
                'sizes'             => ['Shampoo + Conditioner Combo'],
                'short_description' => 'Argan oil infused anti-frizz shampoo and deep conditioning hair masque.',
                'description'       => '<p>Restores strength, shine, and silky smoothness to damaged, dry, or chemically treated hair follicles.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],

            // --- Home & Living ---
            [
                'title'             => 'Non-Stick Cookware Set',
                'slug'              => 'non-stick-cookware-set',
                'sku'               => 'HOME-NCS-01',
                'category_handle'   => 'home-living',
                'regular_price'     => 4500,
                'sale_price'        => 3600,
                'cost_price'        => 2400,
                'stock'             => 30,
                'sizes'             => ['3 Piece Set', '5 Piece Set'],
                'short_description' => 'Scratch-resistant granite coated induction-compatible frying pans and pots.',
                'description'       => '<p>Enjoy healthy low-oil cooking with food-grade non-stick surface, heat-resistant bakelite handles, and tempered glass lids.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Table Lamp',
                'slug'              => 'table-lamp',
                'sku'               => 'HOME-TL-02',
                'category_handle'   => 'home-living',
                'regular_price'     => 1500,
                'sale_price'        => 1190,
                'cost_price'        => 680,
                'stock'             => 50,
                'sizes'             => ['Warm White', 'Touch Dimming'],
                'short_description' => 'Minimalist Nordic LED desk lamp with adjustable brightness levels.',
                'description'       => '<p>Eye-caring non-flicker LED illumination perfect for bedside reading, office study, and ambient interior styling.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Storage Organizer',
                'slug'              => 'storage-organizer',
                'sku'               => 'HOME-SO-03',
                'category_handle'   => 'home-living',
                'regular_price'     => 950,
                'sale_price'        => 750,
                'cost_price'        => 420,
                'stock'             => 65,
                'sizes'             => ['Small (3 Compartments)', 'Large (6 Compartments)'],
                'short_description' => 'Foldable wardrobe fabric storage bin with transparent view window.',
                'description'       => '<p>Keep closets, blankets, and seasonal clothing neatly organized and protected against dust and moisture.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Premium Cushion Set',
                'slug'              => 'premium-cushion-set',
                'sku'               => 'HOME-PCS-04',
                'category_handle'   => 'home-living',
                'regular_price'     => 1200,
                'sale_price'        => 920,
                'cost_price'        => 550,
                'stock'             => 55,
                'sizes'             => ['Set of 2', 'Set of 4'],
                'short_description' => 'Ultra-soft velvet decorative throw pillows with fluffy micro-fiber filling.',
                'description'       => '<p>Add instant elegance and plush sitting comfort to living room sofas, armchairs, or master bedrooms.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Kitchen Organizer',
                'slug'              => 'kitchen-organizer',
                'sku'               => 'HOME-KO-05',
                'category_handle'   => 'home-living',
                'regular_price'     => 1100,
                'sale_price'        => 850,
                'cost_price'        => 480,
                'stock'             => 70,
                'sizes'             => ['2 Tier Rack', '3 Tier Rack'],
                'short_description' => 'Stainless steel spice rack and countertop utensil drying station.',
                'description'       => '<p>Rust-resistant, stable non-slip organizer that maximizes countertop space for jars, bottles, and cooking essentials.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],

            // --- Grocery ---
            [
                'title'             => 'Premium Basmati Rice',
                'slug'              => 'premium-basmati-rice',
                'sku'               => 'GROC-PBR-01',
                'category_handle'   => 'grocery',
                'regular_price'     => 1100,
                'sale_price'        => 950,
                'cost_price'        => 780,
                'stock'             => 150,
                'sizes'             => ['5 KG Bag', '10 KG Bag'],
                'short_description' => 'Aged extra long grain aromatic royal Basmati rice.',
                'description'       => '<p>Slender, non-sticky grains that expand beautifully upon cooking. Perfect for biryani, polao, and festive dining.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Organic Honey',
                'slug'              => 'organic-honey',
                'sku'               => 'GROC-OH-02',
                'category_handle'   => 'grocery',
                'regular_price'     => 800,
                'sale_price'        => 650,
                'cost_price'        => 400,
                'stock'             => 90,
                'sizes'             => ['500g Jar', '1 KG Jar'],
                'short_description' => '100% pure raw unfiltered wildflower honey directly from natural apiaries.',
                'description'       => '<p>Rich in natural antioxidants, enzymes, and pleasant floral aroma. Excellent natural sweetener for tea and daily immunity.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Green Tea',
                'slug'              => 'green-tea',
                'sku'               => 'GROC-GT-03',
                'category_handle'   => 'grocery',
                'regular_price'     => 450,
                'sale_price'        => 350,
                'cost_price'        => 200,
                'stock'             => 110,
                'sizes'             => ['50 Tea Bags', '100 Tea Bags'],
                'short_description' => 'Pure hand-plucked garden fresh loose leaf green tea.',
                'description'       => '<p>Refreshing detoxifying brew rich in catechins and polyphenols for daily revitalization and metabolism support.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Mixed Nuts',
                'slug'              => 'mixed-nuts',
                'sku'               => 'GROC-MN-04',
                'category_handle'   => 'grocery',
                'regular_price'     => 950,
                'sale_price'        => 780,
                'cost_price'        => 520,
                'stock'             => 80,
                'sizes'             => ['250g Pack', '500g Pack'],
                'short_description' => 'Premium roasted almond, cashew, walnut, and pistachio crunchy mix.',
                'description'       => '<p>Nutritious healthy snack packed with plant-based protein, dietary fiber, and healthy omega fatty acids.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Cooking Oil',
                'slug'              => 'cooking-oil',
                'sku'               => 'GROC-CO-05',
                'category_handle'   => 'grocery',
                'regular_price'     => 900,
                'sale_price'        => 790,
                'cost_price'        => 650,
                'stock'             => 100,
                'sizes'             => ['2 Liter Can', '5 Liter Can'],
                'short_description' => 'Cholesterol-free multi-filtered healthy refined cooking oil.',
                'description'       => '<p>Fortified with Vitamin A and D, providing light, smoke-free frying and everyday kitchen cooking.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],

            // --- Accessories ---
            [
                'title'             => 'Casual Backpack',
                'slug'              => 'casual-backpack',
                'sku'               => 'ACC-CB-01',
                'category_handle'   => 'accessories',
                'regular_price'     => 1900,
                'sale_price'        => 1450,
                'cost_price'        => 850,
                'stock'             => 55,
                'sizes'             => ['Standard 20L', 'Large 30L'],
                'short_description' => 'Water-resistant laptop travel backpack with USB charging port.',
                'description'       => '<p>Includes padded 15.6-inch laptop compartment, ergonomic breathable mesh shoulder straps, and anti-theft hidden pockets.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Leather Wallet',
                'slug'              => 'leather-wallet',
                'sku'               => 'ACC-LW-02',
                'category_handle'   => 'accessories',
                'regular_price'     => 950,
                'sale_price'        => 720,
                'cost_price'        => 380,
                'stock'             => 80,
                'sizes'             => ['Classic Brown', 'Midnight Black'],
                'short_description' => 'Genuine top-grain leather bi-fold wallet with RFID blocking protection.',
                'description'       => '<p>Slim pocket profile featuring 8 card slots, dual currency divider, and a transparent identification window.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Sunglasses',
                'slug'              => 'sunglasses',
                'sku'               => 'ACC-SG-03',
                'category_handle'   => 'accessories',
                'regular_price'     => 1100,
                'sale_price'        => 790,
                'cost_price'        => 410,
                'stock'             => 65,
                'sizes'             => ['Polarized Black', 'Tortoise Shell'],
                'short_description' => 'UV400 polarized classic unisex sunglasses with lightweight alloy frame.',
                'description'       => '<p>Eliminates harsh glare while driving and outdoor sports, providing 100% UVA/UVB optical protection.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Analog Wrist Watch',
                'slug'              => 'analog-wrist-watch',
                'sku'               => 'ACC-AWW-04',
                'category_handle'   => 'accessories',
                'regular_price'     => 2200,
                'sale_price'        => 1650,
                'cost_price'        => 980,
                'stock'             => 40,
                'sizes'             => ['Leather Strap', 'Steel Bracelet'],
                'short_description' => 'Precision Japanese quartz movement timepiece with calendar date display.',
                'description'       => '<p>Sleek mineral crystal glass face, stainless steel casing, and water-resistant rating up to 30 meters.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Travel Organizer',
                'slug'              => 'travel-organizer',
                'sku'               => 'ACC-TO-05',
                'category_handle'   => 'accessories',
                'regular_price'     => 750,
                'sale_price'        => 550,
                'cost_price'        => 290,
                'stock'             => 90,
                'sizes'             => ['Compact Kit', 'Family Travel Bag'],
                'short_description' => 'Waterproof multi-compartment passport, document, and cable pouch.',
                'description'       => '<p>Keep travel documents, foreign currency, boarding passes, and electronic chargers securely in one place.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],

            // --- Health ---
            [
                'title'             => 'Digital Thermometer',
                'slug'              => 'digital-thermometer',
                'sku'               => 'HLTH-DT-01',
                'category_handle'   => 'health',
                'regular_price'     => 550,
                'sale_price'        => 390,
                'cost_price'        => 190,
                'stock'             => 100,
                'sizes'             => [],
                'short_description' => 'Fast 10-second accurate oral and underarm digital medical thermometer.',
                'description'       => '<p>Features clear LCD reading, fever alarm beeper, waterproof tip, and auto power-off function.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'First Aid Kit',
                'slug'              => 'first-aid-kit',
                'sku'               => 'HLTH-FAK-02',
                'category_handle'   => 'health',
                'regular_price'     => 1200,
                'sale_price'        => 920,
                'cost_price'        => 510,
                'stock'             => 60,
                'sizes'             => ['Home & Travel Kit', 'Complete Family Kit'],
                'short_description' => 'Comprehensive emergency medical kit in a durable compact pouch.',
                'description'       => '<p>Loaded with sterile bandages, antiseptic wipes, burn dressing, scissors, tweezers, and medical adhesive tape.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Hot & Cold Gel Pack',
                'slug'              => 'hot-and-cold-gel-pack',
                'sku'               => 'HLTH-HCGP-03',
                'category_handle'   => 'health',
                'regular_price'     => 450,
                'sale_price'        => 320,
                'cost_price'        => 150,
                'stock'             => 85,
                'sizes'             => ['Medium', 'Large'],
                'short_description' => 'Reusable flexible therapy pack for muscle pain, swelling, and injuries.',
                'description'       => '<p>Microwaveable for soothing heat therapy and freezable for targeted cold compress relief.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Posture Support Belt',
                'slug'              => 'posture-support-belt',
                'sku'               => 'HLTH-PSB-04',
                'category_handle'   => 'health',
                'regular_price'     => 900,
                'sale_price'        => 680,
                'cost_price'        => 340,
                'stock'             => 70,
                'sizes'             => ['M', 'L', 'XL'],
                'short_description' => 'Ergonomic adjustable back and clavicle posture correction brace.',
                'description'       => '<p>Relieves upper back strain and trains spinal alignment during long office desk and driving hours.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Personal Care Kit',
                'slug'              => 'personal-care-kit',
                'sku'               => 'HLTH-PCK-05',
                'category_handle'   => 'health',
                'regular_price'     => 1400,
                'sale_price'        => 1050,
                'cost_price'        => 580,
                'stock'             => 50,
                'sizes'             => ['Complete Care Set'],
                'short_description' => 'Complete hygiene and daily grooming set in a portable travel case.',
                'description'       => '<p>Includes nail clippers, safety scissors, tweezers, glass file, and personal grooming instruments in a zippered leatherette box.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],

            // --- Sports ---
            [
                'title'             => 'Yoga Mat',
                'slug'              => 'yoga-mat',
                'sku'               => 'SPRT-YM-01',
                'category_handle'   => 'sports',
                'regular_price'     => 1300,
                'sale_price'        => 990,
                'cost_price'        => 520,
                'stock'             => 65,
                'sizes'             => ['6mm Thickness', '8mm Thickness'],
                'short_description' => 'Eco-friendly non-slip cushioned TPE fitness and exercise mat.',
                'description'       => '<p>Superior joint cushioning, textured dual-sided grip, moisture-resistant surface, and convenient carry strap.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Resistance Band Set',
                'slug'              => 'resistance-band-set',
                'sku'               => 'SPRT-RBS-02',
                'category_handle'   => 'sports',
                'regular_price'     => 850,
                'sale_price'        => 620,
                'cost_price'        => 310,
                'stock'             => 95,
                'sizes'             => ['Set of 5 Bands'],
                'short_description' => 'Natural latex workout loop bands with varying resistance levels.',
                'description'       => '<p>Perfect for home fitness, physical therapy, strength building, glute activation, and mobility exercises.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Football',
                'slug'              => 'football',
                'sku'               => 'SPRT-FB-03',
                'category_handle'   => 'sports',
                'regular_price'     => 1100,
                'sale_price'        => 850,
                'cost_price'        => 440,
                'stock'             => 50,
                'sizes'             => ['Size 5 Official'],
                'short_description' => 'Official standard size-5 all-weather stitched outdoor match ball.',
                'description'       => '<p>High-durability synthetic PU leather cover with butyl bladder for optimal air and shape retention.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Sports Water Bottle',
                'slug'              => 'sports-water-bottle',
                'sku'               => 'SPRT-SWB-04',
                'category_handle'   => 'sports',
                'regular_price'     => 650,
                'sale_price'        => 460,
                'cost_price'        => 220,
                'stock'             => 120,
                'sizes'             => ['750ml', '1000ml'],
                'short_description' => 'BPA-free leakproof gym bottle with one-click flip lid and time marker.',
                'description'       => '<p>Durable Eastman Tritan plastic with carrying strap, fast water flow nozzle, and motivational hydration markers.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Skipping Rope',
                'slug'              => 'skipping-rope',
                'sku'               => 'SPRT-SR-05',
                'category_handle'   => 'sports',
                'regular_price'     => 450,
                'sale_price'        => 290,
                'cost_price'        => 130,
                'stock'             => 140,
                'sizes'             => ['Adjustable Speed Rope'],
                'short_description' => 'High-speed 360-degree ball bearing jump rope with anti-slip foam handles.',
                'description'       => '<p>Tangle-free steel wire cable designed for cardio training, calorie burning, and boxing fitness routines.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],

            // --- Books ---
            [
                'title'             => 'Personal Development Book',
                'slug'              => 'personal-development-book',
                'sku'               => 'BOOK-PDB-01',
                'category_handle'   => 'books',
                'regular_price'     => 450,
                'sale_price'        => 360,
                'cost_price'        => 190,
                'stock'             => 80,
                'sizes'             => ['Paperback', 'Hardcover'],
                'short_description' => 'Bestselling guide on mindset, productivity, and personal transformation.',
                'description'       => '<p>Practical actionable techniques to build lasting habits, sharpen focus, and achieve professional and personal goals.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Business Strategy Book',
                'slug'              => 'business-strategy-book',
                'sku'               => 'BOOK-BSB-02',
                'category_handle'   => 'books',
                'regular_price'     => 550,
                'sale_price'        => 440,
                'cost_price'        => 230,
                'stock'             => 60,
                'sizes'             => ['Paperback'],
                'short_description' => 'Proven principles for modern entrepreneurship, scaling, and market leadership.',
                'description'       => '<p>Case studies and strategic frameworks designed for startup founders, executives, and marketing leaders.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'English Learning Book',
                'slug'              => 'english-learning-book',
                'sku'               => 'BOOK-ELB-03',
                'category_handle'   => 'books',
                'regular_price'     => 400,
                'sale_price'        => 320,
                'cost_price'        => 160,
                'stock'             => 100,
                'sizes'             => ['Standard Edition'],
                'short_description' => 'Comprehensive spoken and communicative grammar guidebook with exercises.',
                'description'       => '<p>Step-by-step vocabulary builder, daily conversational dialogues, and practical pronunciation practice.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => "Children's Story Book",
                'slug'              => 'childrens-story-book',
                'sku'               => 'BOOK-CSB-04',
                'category_handle'   => 'books',
                'regular_price'     => 350,
                'sale_price'        => 280,
                'cost_price'        => 140,
                'stock'             => 90,
                'sizes'             => ['Illustrated Edition'],
                'short_description' => 'Engaging full-color illustrated bedtime and moral stories for young readers.',
                'description'       => '<p>Nurtures imagination, language development, and ethical values through delightful illustrated tales.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Cooking Recipe Book',
                'slug'              => 'cooking-recipe-book',
                'sku'               => 'BOOK-CRB-05',
                'category_handle'   => 'books',
                'regular_price'     => 600,
                'sale_price'        => 480,
                'cost_price'        => 260,
                'stock'             => 50,
                'sizes'             => ['Hardcover Collector'],
                'short_description' => 'Authentic regional and continental gourmet cooking recipes with full color photos.',
                'description'       => '<p>Step-by-step culinary instructions for appetizers, main courses, traditional curries, and mouthwatering desserts.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],

            // --- Automotive ---
            [
                'title'             => 'Car Phone Holder',
                'slug'              => 'car-phone-holder',
                'sku'               => 'AUTO-CPH-01',
                'category_handle'   => 'automotive',
                'regular_price'     => 750,
                'sale_price'        => 550,
                'cost_price'        => 270,
                'stock'             => 90,
                'sizes'             => ['Dashboard Suction', 'Air Vent Clip'],
                'short_description' => '360-degree rotation secure magnetic auto-lock car phone cradle.',
                'description'       => '<p>One-hand operation, quick snap release, and shock-resistant grip ensuring your phone stays stable over bumpy roads.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Car Cleaning Kit',
                'slug'              => 'car-cleaning-kit',
                'sku'               => 'AUTO-CCK-02',
                'category_handle'   => 'automotive',
                'regular_price'     => 1400,
                'sale_price'        => 1080,
                'cost_price'        => 550,
                'stock'             => 50,
                'sizes'             => ['5-Piece Wash Set'],
                'short_description' => 'Microfiber wash mitts, detailing brushes, and scratch-free drying towels.',
                'description'       => '<p>Complete professional auto detailing kit for exterior washing, wheel cleaning, and interior dashboard dust removal.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'LED Interior Light',
                'slug'              => 'led-interior-light',
                'sku'               => 'AUTO-LIL-03',
                'category_handle'   => 'automotive',
                'regular_price'     => 850,
                'sale_price'        => 620,
                'cost_price'        => 310,
                'stock'             => 75,
                'sizes'             => ['RGB with Remote'],
                'short_description' => 'Multicolor car footwell atmosphere ambient lighting strip with sound sensor.',
                'description'       => '<p>Easy plug-and-play USB/cigarette lighter connection with multiple color modes and music sync pulsing.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Car Air Freshener',
                'slug'              => 'car-air-freshener',
                'sku'               => 'AUTO-CAF-04',
                'category_handle'   => 'automotive',
                'regular_price'     => 400,
                'sale_price'        => 290,
                'cost_price'        => 120,
                'stock'             => 150,
                'sizes'             => ['Ocean Breeze', 'Vanilla Lemon'],
                'short_description' => 'Long-lasting natural essential oil vent clip fragrance diffuser.',
                'description'       => '<p>Eliminates odors, smoke, and musty air, leaving a crisp, refreshing luxury scent inside the car cabin for 60+ days.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Emergency Tool Kit',
                'slug'              => 'emergency-tool-kit',
                'sku'               => 'AUTO-ETK-05',
                'category_handle'   => 'automotive',
                'regular_price'     => 2200,
                'sale_price'        => 1690,
                'cost_price'        => 950,
                'stock'             => 40,
                'sizes'             => ['Universal Roadside Kit'],
                'short_description' => 'Heavy duty battery booster jumper cables, tow strap, and safety triangle.',
                'description'       => '<p>Essential roadside assistance emergency package complete with tire pressure gauge, gloves, and reflective warning gear.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],

            // --- Toys & Games ---
            [
                'title'             => 'Building Blocks Set',
                'slug'              => 'building-blocks-set',
                'sku'               => 'TOY-BBS-01',
                'category_handle'   => 'toys-games',
                'regular_price'     => 1200,
                'sale_price'        => 890,
                'cost_price'        => 430,
                'stock'             => 70,
                'sizes'             => ['100 Pieces', '250 Pieces'],
                'short_description' => 'Creative architectural interlocking plastic construction blocks for kids.',
                'description'       => '<p>Sparks spatial reasoning, engineering creativity, and fine motor skills with colorful, child-safe non-toxic ABS blocks.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Educational Puzzle',
                'slug'              => 'educational-puzzle',
                'sku'               => 'TOY-EP-02',
                'category_handle'   => 'toys-games',
                'regular_price'     => 600,
                'sale_price'        => 450,
                'cost_price'        => 210,
                'stock'             => 85,
                'sizes'             => ['World Map', 'Animal Kingdom'],
                'short_description' => 'Wooden jigsaw puzzle promoting problem-solving and cognitive matching skills.',
                'description'       => '<p>Smooth laser-cut wooden pieces with vibrant water-based colors designed for toddlers and elementary children.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => false,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Board Game',
                'slug'              => 'board-game',
                'sku'               => 'TOY-BG-03',
                'category_handle'   => 'toys-games',
                'regular_price'     => 900,
                'sale_price'        => 690,
                'cost_price'        => 350,
                'stock'             => 60,
                'sizes'             => ['Family Classic Edition'],
                'short_description' => 'Strategy and trading family board game for 2 to 6 players.',
                'description'       => '<p>Fun, interactive evening tabletop game fostering tactical negotiation, resource management, and family bonding.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
            [
                'title'             => 'Remote Control Car',
                'slug'              => 'remote-control-car',
                'sku'               => 'TOY-RCC-04',
                'category_handle'   => 'toys-games',
                'regular_price'     => 1800,
                'sale_price'        => 1350,
                'cost_price'        => 750,
                'stock'             => 45,
                'sizes'             => ['Speed Buggy Red', 'Speed Buggy Blue'],
                'short_description' => 'High speed 2.4GHz rechargeable all-terrain stunt racing buggy.',
                'description'       => '<p>Shockproof suspension, durable anti-collision bumper, and strong motor delivering thrilling stunts on indoor and outdoor tracks.</p>',
                'is_featured'       => false,
                'is_new_arrival'    => true,
                'is_bestseller'     => true,
            ],
            [
                'title'             => 'Kids Drawing Kit',
                'slug'              => 'kids-drawing-kit',
                'sku'               => 'TOY-KDK-05',
                'category_handle'   => 'toys-games',
                'regular_price'     => 750,
                'sale_price'        => 560,
                'cost_price'        => 280,
                'stock'             => 95,
                'sizes'             => ['50 Color Art Set'],
                'short_description' => 'Complete coloring kit with washable markers, crayons, and sketch pad.',
                'description'       => '<p>Portable art case packed with non-toxic watercolor pens, oil pastels, colored pencils, and creative drawing tools.</p>',
                'is_featured'       => true,
                'is_new_arrival'    => false,
                'is_bestseller'     => false,
            ],
        ];

        foreach ($productsData as $prodData) {
            $cat = $categoryMap[$prodData['category_handle']] ?? null;
            $seedFeatured = '/uploads/products/' . $prodData['slug'] . '.svg';
            $existingProd = Product::where('sku', $prodData['sku'])->first();

            if (!$existingProd) {
                Product::create([
                    'title'             => $prodData['title'],
                    'slug'              => $prodData['slug'],
                    'sku'               => $prodData['sku'],
                    'category_id'       => $cat ? $cat->id : null,
                    'category_handle'   => $prodData['category_handle'],
                    'regular_price'     => $prodData['regular_price'],
                    'sale_price'        => $prodData['sale_price'],
                    'cost_price'        => $prodData['cost_price'] ?? 0,
                    'stock'             => $prodData['stock'] ?? 50,
                    'sizes'             => $prodData['sizes'] ?? [],
                    'featured_image'    => $seedFeatured,
                    'hover_image'       => null,
                    'gallery_images'    => [$seedFeatured],
                    'short_description' => $prodData['short_description'],
                    'description'       => $prodData['description'],
                    'is_featured'       => (bool)($prodData['is_featured'] ?? false),
                    'is_new_arrival'    => (bool)($prodData['is_new_arrival'] ?? false),
                    'is_bestseller'     => (bool)($prodData['is_bestseller'] ?? false),
                    'is_clearance'      => false,
                    'status'            => true,
                ]);
            } else {
                // Safe preservation of admin custom media
                $isSeedOrEmptyFeatured = empty($existingProd->featured_image)
                    || $existingProd->featured_image === '/images/logo.png'
                    || $existingProd->featured_image === '/images/placeholder.webp'
                    || $existingProd->featured_image === $seedFeatured;

                $featuredImage = $isSeedOrEmptyFeatured ? $seedFeatured : $existingProd->featured_image;

                $isSeedOrEmptyGallery = empty($existingProd->gallery_images)
                    || $existingProd->gallery_images === [$seedFeatured]
                    || $existingProd->gallery_images === ['/images/logo.png']
                    || $existingProd->gallery_images === [];

                $galleryImages = $isSeedOrEmptyGallery ? [$seedFeatured] : $existingProd->gallery_images;

                $existingProd->update([
                    'title'             => $prodData['title'],
                    'slug'              => $prodData['slug'],
                    'category_id'       => $cat ? $cat->id : null,
                    'category_handle'   => $prodData['category_handle'],
                    'regular_price'     => $prodData['regular_price'],
                    'sale_price'        => $prodData['sale_price'],
                    'cost_price'        => $prodData['cost_price'] ?? 0,
                    'stock'             => $prodData['stock'] ?? 50,
                    'sizes'             => $prodData['sizes'] ?? [],
                    'featured_image'    => $featuredImage,
                    'hover_image'       => $existingProd->hover_image,
                    'gallery_images'    => $galleryImages,
                    'short_description' => $prodData['short_description'],
                    'description'       => $prodData['description'],
                    'is_featured'       => (bool)($prodData['is_featured'] ?? false),
                    'is_new_arrival'    => (bool)($prodData['is_new_arrival'] ?? false),
                    'is_bestseller'     => (bool)($prodData['is_bestseller'] ?? false),
                    'is_clearance'      => false,
                    'status'            => true,
                ]);
            }
        }
    }
}
